Zorbus\NewsletterBundle\Entity\User:
    type: entity
    table: zorbus_newsletter_user
    repositoryClass: Zorbus\NewsletterBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: false
        parameters:
            type: string
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        created_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        newsletter:
            targetEntity: Zorbus\NewsletterBundle\Entity\Newsletter
            inversedBy: users
            joinColumn:
                name: newsletter_id
                referencedColumnName: id
                onDelete: SET NULL